-- =============================================================================
-- 03_fact_bacen_monthly.sql
-- DEPRECATED — fact_bacen_monthly is dropped and not rebuilt.
--
-- The raw tables ARE still populated: src/pipeline/run_daily.py runs
-- BacenIngestor every day (a 30-day trailing refresh into bacen_sgs,
-- bacen_ptax and bacen_expectativas), and the dashboard's /macro page reads
-- them directly through the build-time connection. What was removed is only
-- this monthly matview: the analytical functions take the benchmark rate as a
-- parameter (benchmark_rate NUMERIC DEFAULT NULL) instead of joining it.
--
-- Nothing in schema `api` reads a bacen_* table (docs/DATA_INVENTORY.md §3
-- lists the macro series as held-not-served), and mv_savings_flow_monthly —
-- the one analytical reader of bacen_sgs — is revoked from every client role.
--
-- An earlier version of this header said the pipeline no longer ingested
-- BACEN. It does; the claim was wrong and the ops page would have shown the
-- rows landing daily.
-- =============================================================================

-- This file is intentionally a no-op. The DROP was applied in migration
-- "drop_bacen_analytical_objects". Re-running this file is safe.

-- Manual refresh command (if re-enabled):
-- REFRESH MATERIALIZED VIEW CONCURRENTLY fact_bacen_monthly;
