-- =============================================================================
-- 03_fact_bacen_monthly.sql
-- DEPRECATED — BACEN data is no longer replicated locally.
--
-- Benchmark comparisons (CDI, SELIC, IPCA) are handled client-side by
-- fetching from the BCB public API at query time and passing the rate as a
-- parameter to the analytical functions (benchmark_rate NUMERIC DEFAULT NULL).
--
-- BCB API endpoints:
--   CDI  (code 12): https://api.bcb.gov.br/dados/serie/bcdata.sgs.12/dados/ultimos/1?formato=json
--   SELIC(code 11): https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados/ultimos/1?formato=json
--   IPCA (code 433):https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados/ultimos/1?formato=json
--
-- Raw tables (bacen_sgs, bacen_ptax, bacen_expectativas) are kept in the schema
-- but are no longer populated by the pipeline.
--
-- To restore BACEN ingestion in future, re-add BacenIngestor to run_daily.py
-- and rebuild this matview.
-- =============================================================================

-- This file is intentionally a no-op. The DROP was applied in migration
-- "drop_bacen_analytical_objects". Re-running this file is safe.

-- Manual refresh command (if re-enabled):
-- REFRESH MATERIALIZED VIEW CONCURRENTLY fact_bacen_monthly;
