#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

#
# SILO-BZ: rotating the database owner's password (postgres on Supabase).
# Run from the repo root on your own machine:  bash scripts/rotate_db_password.sh
#
# Order of events: you reset the password in the Supabase dashboard FIRST, then
# run this. It never prints the password, and it tests the new login BEFORE it
# writes anything, so a typo leaves .env and the GitHub secret untouched.
#
# Where the owner's password lives (checked 2026-10-05):
#   .env on your machine      POSTGRES_URL, SUPABASE_POOLER_URL  (this script)
#   GitHub secret             POSTGRES_URL, the session-pooler URL (this script)
#   Vercel, silo-bz           EVIDENCE_SOURCE__supabase__password, one variable
#                             for production and preview (stage 4, by hand)
# Not affected: the Sentinel (its own role and password), the silo-mcp edge
# function and the Cloudflare engine (public anon key), SUPABASE_ACCESS_TOKEN.
#
# Neither GitHub secrets nor Vercel "sensitive" variables can be read back, so
# there is nothing to pull: the new password goes from here to them.

TOTAL_STAGES=4

# try_login URL: a login attempt. On failure it shows the first line of the
# Postgres message and the usual cause, so a failed connection is not a guessing
# game. libpq's connection errors do not carry the password; the one message that
# quotes a piece of the URL (a bad percent-encoding) is replaced, since that piece
# may be part of it.
try_login() {
  local url="$1" err
  if err=$(psql "$url" -X -At -v ON_ERROR_STOP=1 -c "select 1" 2>&1 >/dev/null); then return 0; fi
  err=$(printf '%s' "$err" | head -n1 | cut -c1-220)
  case "$err" in
    *"invalid percent"*) err="invalid percent-encoded token in the URL (not shown: it may be part of the password)" ;;
  esac
  note "Postgres said: $err"
  case "$err" in
    *"password authentication failed"*)
      say "Cause: wrong password, or one with @ / : # ? that is not percent-encoded in the URL." ;;
    *"Tenant or user not found"*)
      say "Cause: the user must be postgres.<project-ref>, and the host the one in Supabase → Connect → Session pooler." ;;
    *"translate host name"*|*"Name or service not known"*)
      say "Cause: the host in the URL is mistyped (or there is no network)." ;;
    *"invalid"*URI*|*"invalid percent"*)
      say "Cause: the URL is malformed: no quotes or spaces, special characters percent-encoded." ;;
  esac
  return 1
}

banner "SILO-BZ: rotate the database password"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
[[ -f AGENTS.md && -f .gitignore ]] || { warn "run this from the SILO-BZ repo root"; exit 1; }
for tool in gh psql python3; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing: $tool (install it, then re-run)"; exit 1; }
done
gh auth status >/dev/null 2>&1 || { warn "gh is not logged in: run 'gh auth login', then re-run"; exit 1; }
gh repo view PedroDnT/SILO-BZ >/dev/null 2>&1 || { warn "gh cannot see PedroDnT/SILO-BZ with this login"; exit 1; }
OLD_POOLER=$(_existing SUPABASE_POOLER_URL || true)
OLD_DIRECT=$(_existing POSTGRES_URL || true)
# Strip one pair of surrounding quotes, if the .env has them.
OLD_POOLER="${OLD_POOLER%\"}"; OLD_POOLER="${OLD_POOLER#\"}"
OLD_DIRECT="${OLD_DIRECT%\"}"; OLD_DIRECT="${OLD_DIRECT#\"}"
if [[ -z "$OLD_POOLER" ]]; then
  warn "SUPABASE_POOLER_URL is not in $ENV_FILE."
  say  "Put the session-pooler URI there first (Supabase → Connect → Session pooler),"
  say  "with any password in it: this script replaces the password part."
  exit 1
fi
say "gh, psql and python3 are here; gh sees PedroDnT/SILO-BZ."
if [[ -n "$OLD_DIRECT" ]]; then say "$ENV_FILE has the session-pooler URL and POSTGRES_URL."
else say "$ENV_FILE has the session-pooler URL (no POSTGRES_URL: only the pooler URL is saved)."; fi
open_url "https://supabase.com/dashboard/project/zcjbtpxuhdekpwcxmepn/database/settings"
step "If you have not yet: Database → Settings → Reset database password,"
step "generate or type a new one, and copy it. Do not close the page before you paste it here."
pause "Done resetting it in Supabase?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The new password, tested before anything is written"
ask_secret NEW_DB_PASSWORD "Paste the new database password (hidden):"
[[ -n "$NEW_DB_PASSWORD" ]] || { warn "empty password: nothing changed"; exit 1; }
# Rebuild a URL with the new password, keeping user, host, port, path, query.
# The password goes in through the environment, never through argv.
with_password() {  # with_password URL
  URL="$1" PW="$NEW_DB_PASSWORD" python3 - <<'PY'
import os, re, urllib.parse as u
# The old URL is only read for its user, scheme and host: the old password in it
# is being replaced, so it may hold characters that break a strict URL parse
# (a "/", "?" or "#" that was never percent-encoded) and is never parsed.
url = os.environ["URL"].strip()
if len(url) >= 2 and url[0] == url[-1] and url[0] in "'\"":
    url = url[1:-1].strip()
m = re.match(r"^([A-Za-z][A-Za-z0-9+.-]*)://(.*)$", url, re.S)
if not m or m.group(1) not in ("postgres", "postgresql"):
    raise SystemExit("the URL in .env does not start with postgresql:// (quotes and spaces are fine)")
if "@" not in m.group(2):
    raise SystemExit("the URL in .env has no user@host part")
userinfo, hostpart = m.group(2).rsplit("@", 1)  # the host part has no "@"
user = userinfo.split(":", 1)[0]
tail = u.urlsplit("//" + hostpart)
if not user or not tail.hostname:
    raise SystemExit("the URL in .env has no user or host")
query = f"?{tail.query}" if tail.query else ""
print(f"{m.group(1)}://{user}:{u.quote(os.environ['PW'], safe='')}@{tail.netloc}{tail.path}{query}")
PY
}
NEW_POOLER=$(with_password "$OLD_POOLER") || { warn "could not rebuild the pooler URL"; exit 1; }
if try_login "$NEW_POOLER"; then
  say "The new password logs in through the session pooler."
else
  warn "the new password did NOT log in through the pooler."
  say  "Nothing was changed. Check that you pasted the one from the Supabase reset,"
  say  "and that SUPABASE_POOLER_URL in $ENV_FILE has the right user (postgres.<project-ref>)."
  exit 1
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Save it: .env and the GitHub secret"
say ".env gets the new password in SUPABASE_POOLER_URL and in POSTGRES_URL."
say "The GitHub secret POSTGRES_URL gets the session-pooler URL (CI runners are"
say "IPv4 only, and the direct host is IPv6 only), as scripts/finish_cutover.sh does."
confirm "Write them now?" || { warn "nothing was written"; exit 1; }
write_env SUPABASE_POOLER_URL "$NEW_POOLER"
if [[ -n "$OLD_DIRECT" ]]; then
  NEW_DIRECT=$(with_password "$OLD_DIRECT") || { warn "could not rebuild POSTGRES_URL; left as it was"; NEW_DIRECT=""; }
  [[ -n "$NEW_DIRECT" ]] && write_env POSTGRES_URL "$NEW_DIRECT"
fi
# CI needs the IPv4 session pooler (the ingest and the analytical apply use session
# features, which a transaction pooler on 6543 does not give; scripts/apply_analytical.sh).
# A login that works from this machine on another host, such as the dedicated pooler
# db.<ref>.supabase.co:6543, must not overwrite the secret.
case "$NEW_POOLER" in
  *.pooler.supabase.com:5432/*)
    set_secret POSTGRES_URL "$NEW_POOLER" ;;
  *)
    warn "The GitHub secret POSTGRES_URL was NOT touched."
    say  "CI needs the session pooler (aws-*.pooler.supabase.com, port 5432); the URL now in"
    say  "$ENV_FILE points elsewhere. Set the secret from a session-pooler URL when you have one."
    SKIPPED+=("GitHub secret POSTGRES_URL: the URL is not a session-pooler URL") ;;
esac
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Vercel: the dashboard's password"
say "The dashboard build reads EVIDENCE_SOURCE__supabase__password. It is one"
say "variable for production and preview, so one edit covers both."
copied=0
for clip in pbcopy wl-copy "xclip -selection clipboard" clip.exe; do
  if command -v "${clip%% *}" >/dev/null 2>&1; then
    printf '%s' "$NEW_DB_PASSWORD" | $clip && copied=1 && break
  fi
done
if (( copied )); then say "The new password is on your clipboard."
else warn "no clipboard tool found: copy the password from the Supabase page"; fi
open_url "https://vercel.com/deloslabs/silo-bz/settings/environment-variables"
step "Find EVIDENCE_SOURCE__supabase__password → ⋯ → Edit."
step "Paste the new password as the value. Leave Production and Preview ticked. Save."
step "Do not touch the other EVIDENCE_SOURCE__supabase__* variables."
note "A deployment already built keeps the old value; the next build uses the new one."
pause "Saved it in Vercel?"

finish
say "Now ask Claude to check it: it can run health.yml (tests the GitHub secret) and"
say "a dashboard build (tests the Vercel value), so a mistake shows up now and not"
say "at the 03:00 daily run."
printf '\n'
