#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

#
# SILO-BZ: the owner's steps for the B7 agent loop (docs/planning/OPEN_ITEMS.md
# item 13, docs/planning/AGENTS.md §2 "Sentinel credential" and §6).
# Run from the repo root on your own machine:  bash scripts/setup_agents_wizard.sh
# Re-running is safe: labels are upserted, and the Sentinel's password is kept
# unless you choose to rotate it. Nothing secret is ever printed.

REPO="PedroDnT/SILO-BZ"
ROLE_SQL="docs/reference/security/sentinel_readonly_role.sql"

TOTAL_STAGES=6

# try_login URL: a login attempt. On failure it shows the first line of the
# Postgres message and the usual cause, so a failed connection is not a guessing
# game. libpq's connection errors do not carry the password; the one message that
# quotes a piece of the URL (a bad percent-encoding) is replaced, since that piece
# may be part of it.
try_login() {
  local url="$1" err
  if err=$(psql "$url" -X -At -v ON_ERROR_STOP=1 -c "select 1" 2>&1 >/dev/null); then return 0; fi
  err=$(printf '%s' "$err" | head -n1 | cut -c1-220)
  case "$err" in
    *"invalid percent"*) err="invalid percent-encoded token in the URL (not shown: it may be part of the password)" ;;
  esac
  note "Postgres said: $err"
  case "$err" in
    *"password authentication failed"*)
      say "Cause: wrong password, or one with @ / : # ? that is not percent-encoded in the URL." ;;
    *"Tenant or user not found"*)
      say "Cause: the user must be postgres.<project-ref>, and the host the one in Supabase → Connect → Session pooler." ;;
    *"translate host name"*|*"Name or service not known"*)
      say "Cause: the host in the URL is mistyped (or there is no network)." ;;
    *"invalid"*URI*|*"invalid percent"*)
      say "Cause: the URL is malformed: no quotes or spaces, special characters percent-encoded." ;;
  esac
  return 1
}

banner "SILO-BZ: agent labels and the Sentinel's read-only database role"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
[[ -f "$ROLE_SQL" && -f AGENTS.md ]] || { warn "run this from the SILO-BZ repo root"; exit 1; }
for tool in gh psql openssl python3; do
  command -v "$tool" >/dev/null 2>&1 || { warn "missing: $tool (install it, then re-run)"; exit 1; }
done
gh auth status >/dev/null 2>&1 || { warn "gh is not logged in: run 'gh auth login', then re-run"; exit 1; }
gh repo view "$REPO" >/dev/null 2>&1 || { warn "gh cannot see $REPO with this login"; exit 1; }
say "gh, psql, openssl and python3 are here, and gh sees $REPO."
OWNER_URL=$(_existing SUPABASE_POOLER_URL || true)
if [[ -z "$OWNER_URL" ]]; then
  say "The Sentinel runs in the cloud, where the direct host db.<ref>.supabase.co"
  say "(IPv6 only) is not reachable, so its URL is built on the session pooler."
  open_url "https://supabase.com/dashboard/project/zcjbtpxuhdekpwcxmepn"
  step "Click Connect (top of the project page), pick Session pooler, copy the URI."
  step "Replace [YOUR-PASSWORD] in it with the postgres password (the one in POSTGRES_URL)."
  ask_secret SUPABASE_POOLER_URL "Paste the session-pooler URI (hidden):"
  OWNER_URL="$SUPABASE_POOLER_URL"
  write_env SUPABASE_POOLER_URL "$OWNER_URL"
fi
# A value copied into .env often carries quotes or a stray space; psql would read
# it as a database name and look for a local server.
OWNER_URL="${OWNER_URL#"${OWNER_URL%%[![:space:]]*}"}"
OWNER_URL="${OWNER_URL%"${OWNER_URL##*[![:space:]]}"}"
case "$OWNER_URL" in
  \'*\'|\"*\") OWNER_URL="${OWNER_URL:1:${#OWNER_URL}-2}" ;;
esac
if ! try_login "$OWNER_URL"; then
  warn "could not connect with SUPABASE_POOLER_URL from $ENV_FILE: fix it there and re-run"
  exit 1
fi
say "Connected to the database as its owner, through the pooler."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub labels"
say "Each agent prompt stops at once while its label is missing (AGENTS.md §6)."
say "The Builder takes issues labelled ready-for-agent (triage), which already exists."
create_label() {
  gh label create "$1" -R "$REPO" --color "$2" --description "$3" --force >/dev/null
  printf '  %s✓ label%s %s\n' "$GREEN" "$RESET" "$1"
}
create_label "agent:builder"  "5319E7" "Opened by the Builder agent (.claude/agents/builder.md)"
create_label "agent:sentinel" "5319E7" "Opened by the Sentinel agent (.claude/agents/sentinel.md)"
create_label "agent:scout"    "5319E7" "Opened by the Scout agent (.claude/agents/scout.md)"
note "You apply ready-for-agent to an issue; the agents never do."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The Sentinel's password"
SENTINEL_DB_PASSWORD=$(_existing SENTINEL_DB_PASSWORD || true)
if [[ -n "$SENTINEL_DB_PASSWORD" ]] && ! confirm "A password is already in $ENV_FILE. Rotate it?"; then
  say "Keeping the current password."
else
  # Hex only: safe inside a connection URL with no escaping.
  SENTINEL_DB_PASSWORD=$(openssl rand -hex 24)
  write_env SENTINEL_DB_PASSWORD "$SENTINEL_DB_PASSWORD"
  say "Generated a new 48-character password. It is not shown."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the role silo_sentinel"
say "This runs $ROLE_SQL as the database owner. It creates (or re-passwords)"
say "a LOGIN role that can only: connect; read cvm_ingest_log and fnet_document;"
say "call api.coverage() and api.metric_coverage(); 30 s per statement."
say "Then it sets default_transaction_read_only = on for the role."
note "No table, row or other role is touched."
if confirm "Run it against production now?"; then
  psql "$OWNER_URL" -X -q -v ON_ERROR_STOP=1 \
       -v sentinel_password="$SENTINEL_DB_PASSWORD" -f "$ROLE_SQL" >/dev/null
  psql "$OWNER_URL" -X -q -v ON_ERROR_STOP=1 \
       -c "ALTER ROLE silo_sentinel SET default_transaction_read_only = on;" >/dev/null
  printf '  %s✓ role%s silo_sentinel ready\n' "$GREEN" "$RESET"
else
  warn "skipped: nothing changed in the database. Re-run when ready."
  SKIPPED+=("the silo_sentinel role (stage 4)")
  finish; exit 0
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Test the Sentinel's login"
# The pooler user is <role>.<project-ref>; read from the environment, never argv.
SENTINEL_DATABASE_URL=$(OWNER_URL="$OWNER_URL" PW="$SENTINEL_DB_PASSWORD" python3 - <<'PY'
import os, urllib.parse as u
p = u.urlsplit(os.environ["OWNER_URL"])
ref = (p.username or "").split(".", 1)[1] if "." in (p.username or "") else ""
if not ref:
    raise SystemExit("SUPABASE_POOLER_URL's user is not postgres.<project-ref>")
host = p.hostname + (f":{p.port}" if p.port else "")
print(u.urlunsplit((p.scheme, f"silo_sentinel.{ref}:{os.environ['PW']}@{host}", p.path, p.query, "")))
PY
)
check() {  # check "label" "SQL" "expected"
  local got
  got=$(psql "$SENTINEL_DATABASE_URL" -X -At -v ON_ERROR_STOP=1 -c "$2" 2>/dev/null || echo "ERROR")
  if [[ "$got" == "$3" ]]; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else warn "$1: expected '$3', got '$got'"; FAILED=1; fi
}
FAILED=0
check "logs in as silo_sentinel"        "select current_user"                                                      "silo_sentinel"
check "read-only by default"            "show default_transaction_read_only"                                       "on"
check "reads cvm_ingest_log"            "select count(*) > 0 from public.cvm_ingest_log where started_at > now() - interval '3 days'" "t"
check "cannot write cvm_ingest_log"     "select has_table_privilege('public.cvm_ingest_log', 'INSERT')"            "f"
check "api.coverage() answers"          "select count(*) > 0 from api.coverage()"                                  "t"
if (( FAILED )); then
  warn "a check failed: the role exists, but do not hand its URL to the Sentinel yet"
  SKIPPED+=("a passing stage 5 (re-run the wizard after fixing)")
  finish; exit 1
fi
write_env SENTINEL_DATABASE_URL "$SENTINEL_DATABASE_URL"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "A cloud environment for the Sentinel only"
say "The Sentinel routine reads SENTINEL_DATABASE_URL from its environment."
warn "Heads-up (tested 2026-10-05): a cloud sandbox resolved the pooler host but a raw"
warn "TCP connection to port 5432/6543 timed out, while HTTPS worked. DB mode may not"
warn "connect from there; the Sentinel runs in public mode without any credential."
say "Give it an environment of its own, so the Builder and the Scout"
say "(which run in your usual environment) never hold a database credential."
copied=0
for clip in pbcopy wl-copy "xclip -selection clipboard" clip.exe; do
  if command -v "${clip%% *}" >/dev/null 2>&1; then
    printf '%s' "$SENTINEL_DATABASE_URL" | $clip && copied=1 && break
  fi
done
if (( copied )); then say "SENTINEL_DATABASE_URL is on your clipboard."
else note "To copy it: grep '^SENTINEL_DATABASE_URL=' $ENV_FILE | cut -d= -f2-"; fi
open_url "https://claude.ai/code"
step "Open any session, click the cloud environment name in its title bar."
step "Add a new environment (or Edit a copy of yours). Suggested name: silo-sentinel."
step "Repository: $REPO."
step "Environment variable: SENTINEL_DATABASE_URL = (paste)."
step "Network: allow the pooler host, aws-1-sa-east-1.pooler.supabase.com"
step "(or *.pooler.supabase.com), on top of GitHub."
note "The menu names may differ slightly; the variable name must be exact."
ask SENTINEL_ENV_NAME "Name you gave the environment:"
write_env SENTINEL_ENV_NAME "$SENTINEL_ENV_NAME"

finish
say "Last step, in the Claude session: tell it the environment is called"
say "'${SENTINEL_ENV_NAME}', and it creates the three routines (Builder, Sentinel,"
say "Scout) and opens the PR that fills their ids into AGENTS.md §3a."
printf '\n'
